FROM elixir:1.9.0-alpine AS build

RUN apk add elixir
RUN mix local.hex

# install build dependencies
RUN apk add --no-cache build-base npm git python

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new 1.5.4 --force

ARG SECRET_KEY
ARG DB_CONN

# set build ENV
ENV MIX_ENV=db_update \
    SECRET_KEY_BASE=$SECRET_KEY \
    DB_HOST="" \
    DB_NAME="" \
    DB_USER="" \
    DB_PASS="" \
    DB_PORT=""

# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
COPY apps apps

RUN mix do deps.get, deps.compile

# uncomment COPY if rel/ exists
# COPY rel rel
RUN mix do compile

COPY kube_scripts/update_db.sh update_db.sh

CMD ["/bin/sh", "/app/update_db.sh"]
