
kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: tannhauser-gate
          image: tannhauser_gate_test:0.30
          ports:
            - containerPort: 4000
          args: ["bin/tannhauser_gate", "start"]
          env:
            - name: PORT
              value: "4000"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: erlang-cookie
            - name: RELEASE_DISTRIBUTION
              value: "name"
            - name: RELEASE_NAME
              value: "$(MY_POD_NAMESPACE)"
            - name: RELEASE_NODE
              value: "$(MY_POD_NAMESPACE)@$(MY_POD_IP)"
            - name: CHECK_DB
              value: "S"
        - name: kube-proxy
          image: bitnami/kubectl
          imagePullPolicy: Always
          args: ["proxy", "-p", "8001"]
